### YamlMime:AchievementDetail
achievementUid: learn-bizapps.configure-volunteer-management-settings.badge
metadata:
  title: >-
    Microsoft Badge: Configure settings for Volunteer Management was issued by
    Microsoft
socialImageUrl: /learn/achievements/configure-volunteer-management-settings-social.png
