### YamlMime:AchievementDetail
achievementUid: learn-bizapps.post-deployment-configuration.badge
metadata:
  title: >-
    Microsoft Badge: Microsoft Vaccination Management post-deployment
    configuration was issued by Microsoft
socialImageUrl: /learn/achievements/post-deployment-configuration-social.png
