### YamlMime:AchievementDetail
achievementUid: learn-bizapps.financial-training-environment-preparation.badge
metadata:
  title: >-
    Microsoft Badge: Financial Services training environment preparation was
    issued by Microsoft
socialImageUrl: /learn/achievements/financial-training-environment-preparation-social.png
