### YamlMime:AchievementDetail
achievementUid: learn-bizapps.power-bi-admin-environment.badge
metadata:
  title: 'Microsoft Badge: Establish a Power BI environment was issued by Microsoft'
socialImageUrl: /learn/achievements/power-bi-admin-environment-social.png
