### YamlMime:AchievementDetail
achievementUid: learn-bizapps.manage-environmental-changes.badge
metadata:
  title: >-
    Microsoft Badge: Manage environmental changes in Microsoft Power Platform
    was issued by Microsoft
socialImageUrl: /learn/achievements/manage-environmental-changes-social.png
