### YamlMime:AchievementDetail
achievementUid: learn-bizapps.configure-custom-connectors-api.badge
metadata:
  title: >-
    Microsoft Badge: Configure custom connectors with authenticated APIs in
    Power Automate was issued by Microsoft
socialImageUrl: /learn/achievements/configure-custom-connectors-api-social.png
