### YamlMime:AchievementDetail
achievementUid: learn-bizapps.configure-security.badge
metadata:
  title: >-
    Microsoft Badge: Configure Power Apps portals security was issued by
    Microsoft
socialImageUrl: /learn/achievements/configure-security-social.png
