### YamlMime:AchievementDetail
achievementUid: learn.best-practices-environments.trophy
metadata:
  title: >-
    Microsoft Trophy: Use best practices to secure and govern Microsoft Power
    Platform environments was issued by Microsoft
socialImageUrl: /learn/achievements/best-practices-environments-social.png
