### YamlMime:AchievementDetail
achievementUid: learn-bizapps.vaccination-environment-prep.badge
metadata:
  title: >-
    Microsoft Badge: Microsoft Vaccination Management environment preparation
    was issued by Microsoft
socialImageUrl: /learn/achievements/vaccination-environment-prep-social.png
