### YamlMime:AchievementDetail
achievementUid: learn-bizapps.application-lifecycle-management-architect.badge
metadata:
  title: >-
    Microsoft Badge: Solution Architect series: Plan application lifecycle
    management for Power Platform was issued by Microsoft
socialImageUrl: /learn/achievements/application-lifecycle-management-architect-social.png
