### YamlMime:AchievementDetail
achievementUid: learn-bizapps.deployment-planning-healthcare.badge
metadata:
  title: >-
    Microsoft Badge: Deployment planning of Microsoft Cloud for Healthcare was
    issued by Microsoft
socialImageUrl: /learn/achievements/deployment-planning-healthcare-social.png
