### YamlMime:AchievementDetail
achievementUid: learn-bizapps.training-environment-preparation-healthcare.badge
metadata:
  title: >-
    Microsoft Badge: Microsoft Cloud for Healthcare training environment
    preparation was issued by Microsoft
socialImageUrl: /learn/achievements/training-environment-preparation-healthcare-social.png
