### YamlMime:AchievementDetail
achievementUid: learn-bizapps.configure-settings-fundraising-engagement.badge
metadata:
  title: >-
    Microsoft Badge: Configure settings for Fundraising and Engagement was
    issued by Microsoft
socialImageUrl: /learn/achievements/configure-settings-fundraising-engagement-social.png
