### YamlMime:AchievementDetail
achievementUid: learn-bizapps.plan-manage-environment.badge
metadata:
  title: >-
    Microsoft Badge: Plan and manage your Microsoft Power Platform environment
    was issued by Microsoft
socialImageUrl: /learn/achievements/plan-manage-environment-social.png
