### YamlMime:ModuleUnit 
uid: learn-bizapps.power-bi-deployment-pipelines.understand-deployment-process 
title: Understand the deployment process
metadata: 
  title: Understand the deployment process
  description: Learn about continuous integration/continuous deployment (CI/CD) methodology in Power BI Service that ensures content is updated, well-tested, and regularly refreshed as needed.
  ms.date: 07/08/2022 
  author: Heyrob 
  ms.author: Robde 
  ms.topic: interactive-tutorial 
  ms.prod: learning-power-bi 
durationInMinutes: 6
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/understand-deployment-process.md)] 
