### YamlMime:ModuleUnit 
uid: learn-bizapps.power-bi-deployment-pipelines.work-with-deployment-pipelines 
title: Work with deployment pipelines
metadata: 
  title: Work with deployment pipelines
  description: Once you have content in a pipeline stage, you can deploy it to the next stage. 
  ms.date: 07/08/2022 
  author: Heyrob 
  ms.author: Robde 
  ms.topic: interactive-tutorial 
  ms.prod: learning-power-bi 
durationInMinutes: 8
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/work-with-deployment-pipelines.md)] 
