### YamlMime:ModuleUnit 
uid: learn-bizapps.authentication-user-management.2-authentication-settings 
title: Power Apps portals authentication settings
metadata: 
  title: Power Apps portals authentication settings
  description: Learn about authentication settings and categories.
  ms.date: 06/27/2022 
  author: DaveBeasley 
  ms.author: dbeasley 
  ms.topic: interactive-tutorial 
  ms.prod: learning-power-apps 
durationInMinutes: 3
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/2-authentication-settings.md)] 
