### YamlMime:ModuleUnit 
uid: learn-bizapps.build-mobile-optimized.mobile-optimized-applications 
title: Learn about mobile-optimized apps
metadata: 
  title: Learn about mobile-optimized apps
  description: Learn about what makes an application mobile-optimized.
  ms.date: 6/17/2022 
  author: jadaphillips 
  ms.author: jadaphillips 
  ms.topic: interactive-tutorial 
  ms.prod: learning-power-apps 
durationInMinutes: 9 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/mobile-optimized-applications.md)] 
