### YamlMime:ModuleUnit 
uid: learn-bizapps.incorporate-maps-address.configure-address-input 
title: Configure the address input in an app
metadata: 
  title: Configure the address input in an app
  description: Learn to configure the address input in an app.
  ms.date: 06/30/2022 
  author: jadaphillips 
  ms.author: jadaphillips 
  ms.topic: interactive-tutorial 
  ms.prod: learning-power-apps 
durationInMinutes: 3
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/configure-address-input.md)] 
