### YamlMime:ModuleUnit 
uid: learn-bizapps.power-bi-embedded-permissions-analytics.security 
title: Set up row-level security
metadata: 
  title: Set up row-level security
  description: Learn about row-level security.
  ms.date: 04/10/2022 
  author: heyrob 
  ms.author: robde 
  ms.topic: interactive-tutorial 
  ms.prod: learning-power-bi 
durationInMinutes: 9 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/security.md)] 
