### YamlMime:ModuleUnit 
uid: learn-bizapps.explore-portals-studio.settings 
title: Settings and configuration
metadata: 
  title: Settings and configuration
  description: Learn about settings and progressive web apps configuration in Power Apps Studio.  
  ms.date: 06/23/2022 
  author: DaveBeasley 
  ms.author: dbeasley 
  ms.topic: interactive-tutorial 
  ms.prod: learning-power-apps-portals 
durationInMinutes: 3 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/settings.md)] 
