### YamlMime:ModuleUnit
uid: learn-bizapps.power-pages-features.alternate-applications
title: Alternate Power Pages applications
metadata:
  title: Alternate Power Pages applications
  description: Learn about alternate Power Pages applications.
  ms.date: 10/12/2022
  author: heyrob
  ms.author: robde
  ms.topic: interactive-tutorial
  ms.prod: learning-power-pages
durationInMinutes: 2
content: |
 [!include[](../includes/unit-banner.md)]
 [!include[](includes/alternate-applications.md)]
