### YamlMime:ModuleUnit 
uid: learn-bizapps.power-bi-admin-governance.3-configure 
title: Configure tenant settings
metadata: 
  title: Configure tenant settings
  description: Learn to configure tenant settings.
  ms.date: 04/30/2021 
  author: heyrob 
  ms.author: robde 
  ms.topic: interactive-tutorial 
  ms.service: powerbi 
durationInMinutes: 1
content: | 
 [!include[](../../power-bi/includes/unit-banner.md)] 
 [!include[](includes/3-configure.md)] 
