### YamlMime:ModuleUnit
uid: learn-bizapps.intro-portals.4-portal-security
title: Overview of portal security
metadata:
  title: Overview of portal security
  description: Learn about the basics of portal security.
  ms.date: 07/11/2022
  author: DaveBeasley
  ms.author: dbeasley
  ms.topic: interactive-tutorial
  ms.subservice: portals
durationInMinutes: 5
content: |
 [!include[](../includes/unit-banner.md)]
 [!include[](includes/4-portal-security.md)]
