### YamlMime:ModuleUnit
uid: learn-bizapps.integrate-common-data-service.4-web-form-configure
title: Configure advanced forms
metadata:
  title: Configure advanced forms
  description: Learn how to set up advanced form properties and steps and how to add the advanced form to your portal.
  ms.date: 07/12/2022
  author: DaveBeasley
  ms.author: dbeasley
  ms.topic: interactive-tutorial
  ms.prod: learning-power-apps
durationInMinutes: 10
content: |
 [!include[](../includes/unit-banner.md)]
 [!include[](includes/4-web-form-configure.md)]
