### YamlMime:ModuleUnit
uid: learn-bizapps.retail-intelligent-order-management.configure-environment
title: Exercise 2 - Configure IOM environment
metadata:
  title: Exercise 2 - Configure IOM environment
  description: Follow the steps to configure an Intelligent Order Management environment.
  ms.date: 05/02/2022
  author: DaveBeasley
  ms.author: dbeasley
  ms.topic: interactive-tutorial
  ms.prod: learning-industry-solutions
durationInMinutes: 11
content: |
 [!include[](../includes/unit-banner.md)]
 [!include[](includes/configure-environment.md)]
