### YamlMime:ModuleUnit 
uid: learn-bizapps.retail-clarity.configure-clarity 
title: Set up Microsoft Clarity
metadata: 
  title: Set up Microsoft Clarity
  description: Learn how to set up Microsoft Clarity.
  ms.date: 04/22/2022 
  author: DaveBeasley 
  ms.author: dbeasley 
  ms.topic: interactive-tutorial 
  ms.prod: learning-industry-solutions 
durationInMinutes: 6 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/configure-clarity.md)] 
