### YamlMime:ModuleUnit
uid: learn-bizapps.power-pages-intro.security
title: Overview of Power Pages security
metadata:
  title: Overview of Power Pages security
  description: Learn about the basics of Power Pages security.
  ms.date: 10/12/2022
  author: heyrob
  ms.author: robde
  ms.topic: interactive-tutorial
  ms.prod: learning-power-pages
durationInMinutes: 5
content: |
 [!include[](../includes/unit-banner.md)]
 [!include[](includes/security.md)]
